---
title: "input"
author: "Pierre Nouvellet"
date: "2019-07"
---

```{r options, include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
library(knitr)
library(Hmisc)
library(EpiEstim)
library(zoo)
library(latex2exp)
library(tidyr)

opts_chunk$set(collapse = TRUE)

opts_chunk$set(fig.path='figs/', fig.keep='high', 
               dev=c('png'), fig.width=9, fig.height=6, cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
 	       )



```

# input data


load and clean mobility data.

```{r, echo = FALSE}

d_m <- read.csv(file='../inputs/applemobilitytrends-2020-05-16.csv',stringsAsFactors = FALSE)


```


```{r}

d_g <- read.csv(file = 'Global_Mobility_Report.csv',stringsAsFactors = FALSE)
d_g <- d_g[ which(d_g$sub_region_1 == ''),]

##

a <- tidyr::gather(d_g, var,
                   val,
                   `retail_and_recreation_percent_change_from_baseline`:
                     `residential_percent_change_from_baseline`)
b <- tidyr::spread(a, date, val)


b <- b[,-which(names(b) %in% c("sub_region_1","sub_region_2" ))]
b <- b[-which(b$var %in% c('grocery_and_pharmacy_percent_change_from_baseline',
                               'parks_percent_change_from_baseline',
                               'residential_percent_change_from_baseline')) , ]

names(b)[1:3] <- names(d_m)[1:3]

b[,-c(1:3)] <- b[,-c(1:3)]+100
names(b)[-c(1:3)] <- sub(x=paste0('X',sub(x =names(b)[-c(1:3)],pattern = '-',replacement = '.')),
                         pattern = '-',replacement = '.')

d_g <- b
d_g <- d_g[,-which(names(d_g) %in% c('X2020.02.15','X2020.02.16'))]
range(d_g[,-c(1:3)],na.rm=TRUE)

d_g <- cbind(d_g,d_g[,'X2020.05.09'])
names(d_g)[ncol(d_g)] <- 'X2020.05.10'

write.csv(x = d_g, file = 'google.csv')
```

